# Generated by Django 6.0.4 on 2026-05-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paripko_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
