# Generated by Django 5.2.14 on 2026-06-08 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_article_options_article_category_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Биография')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('phone_number', models.CharField(blank=True, max_length=21, verbose_name='Номер телефона')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум-статус')),
                ('notifications_enabled', models.BooleanField(default=False, verbose_name='Получать уведомления')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Формат: {"vk": "url", "vk2": "url"}', null=True, verbose_name='Социальные сети')),
                ('article_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество опубликовыанных статей')),
                ('comment_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество комментариев')),
                ('followers_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество подписчиков')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['user'],
            },
        ),
    ]
