# Generated by Django 5.2.14 on 2026-06-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Сойдет'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к оценке')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка статьи',
                'verbose_name_plural': 'Оценки статей',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='unique_rating_per_user_article')],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сессии')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='myapp.article', verbose_name='Статья')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_view', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр статьи',
                'verbose_name_plural': 'Просмотры статей',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['article', '-viewed_at'], name='myapp_artic_article_f7a1ee_idx'), models.Index(fields=['user', '-viewed_at'], name='myapp_artic_user_id_60e4f1_idx'), models.Index(fields=['session_key'], name='myapp_artic_session_4c9b09_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='myapp.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Закладки',
                'verbose_name_plural': 'Закладки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='unique_bookmark_per_user_article')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'Новый комментарий'), ('reply', 'Ответ на комментарий'), ('like', 'Лайк'), ('mention', 'Упоминание')], max_length=20, verbose_name='Тип уведомления')),
                ('message', models.TextField(blank=True, verbose_name='Текст уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.article', verbose_name='Статья')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.comment', verbose_name='Комментарий')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notification', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='myapp_notif_recipie_a39187_idx'), models.Index(fields=['created_at'], name='myapp_notif_created_92a5b3_idx')],
            },
        ),
    ]
